### PR TITLE
Dollar Sign Added and Right Justified

### LINKED ISSUE #8: FEATURE: UX/UI Improvements to Instructor Report page
# User Story

* As an instructor
* I can see an improved user interface on the instructor report page 
* So that I can I have an improved user experience

### Discussion

On the instructor report page, dollar amounts are not formatted as currency the way they are on the leaderboard page:

Compare:

image

vs.

image

We'd like dollar amounts formatted as currency, and we'd like other numbers right justified rather than left justified in their columns.

### Acceptance Criteria

- [x] Dollar amounts on instructor report page are displayed as currency
- [x] Other numbers are right justified.

### Implementation Todos

Should be a change to the react component that renders the instructor report page.

### PR DESCRIPTION
**Pull request by hancheng-li**
## Overview
In the PR, I added the feature of a dollar sign in front of any column with currency involved and made every column right-justified. 

## Screenshots
Screenshot 2023-11-20 at 5 49 13 PM

## Validation 
You can test the instructor report by going to my development server: https://happycows-hancheng-li-dev.dokku-02.cs.ucsb.edu/

## Tests

- [x] Backend Unit tests (`mvn test`) pass
- [x] Backend Test coverage (`mvn test jacoco:report`) 100%
- [x] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [x] Frontend Unit tests (`npm test`) pass
- [x] Frontend Test coverage (`npm run coverage`) 100%
- [x] Frontend Mutation tests (`npx stryker run`) 100% 
- [x] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #8

### CODE REVIEW

**Review by amgadhawari — COMMENTED** [review]
Looks good to me !!

**Review by pconrad — CHANGES_REQUESTED** [review]
This LGTM... however, the change doesn't fully resolve the issue.

One of the acceptance criteria was this:

image

That means that the other numbers should be right justified as well, not just the dollar amounts.

Also: the dollar amounts in the top of the instructor report should be formatted as currency also, and the numbers right justified.

We can merge this for 5 points, but if we do, will need to remove the "Closes #6" from the description, because this only partially resolves #6.   You can then put in a separate PR for the rest of the changes if you want.

**Comment by hancheng-li** [comment]
> This LGTM... however, the change doesn't fully resolve the issue.
> 
> One of the acceptance criteria was this:
> 
> image
> That means that the other numbers should be right justified as well, not just the dollar amounts.
> 
> Also: the dollar amounts in the top of the instructor report should be formatted as currency also, and the numbers right justified.
> 
> We can merge this for 5 points, but if we do, will need to remove the "Closes #6" from the description, because this only partially resolves #6. You can then put in a separate PR for the rest of the changes if you want.

Sorry, I misunderstood what the issue is asking for. I will go back and make sure all columns are right aligned and also put the dollar sign on the top instructor report. Should be an easy fix.

**Review by pconrad — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
